// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EpubReaderDbContext))]
    [Migration("20260214000000_AddSettingsTable")]
    partial class AddSettingsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastOpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("_chapters")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Chapters");

                    b.Property<string>("_tableOfContents")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TableOfContents");

                    b.HasKey("Id");

                    b.HasIndex("AddedDate");

                    b.HasIndex("LastOpenedDate");

                    b.HasIndex("Title");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Bookmark", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ChapterId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PositionBookId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PositionBookId");

                    b.Property<DateTime>("PositionSavedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("PositionSavedAt");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL")
                        .HasColumnName("Progress");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("BookId", "Type");

                    b.ToTable("Bookmarks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Highlight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("BookId", "Color");

                    b.ToTable("Highlights", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalBooks")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LibraryIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastAccessedAt");

                    b.HasIndex("Title");

                    b.ToTable("LibraryIndexes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReadingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TotalReadingTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.HasIndex("LastReadAt");

                    b.ToTable("ReadingHistories", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReadingPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BookId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChapterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("ReadingPositions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SavedCssStyle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SavedCssStyles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("LastUpdated");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Book", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.EpubMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("BookId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CalibreId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CoverImagePath")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Creators")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EpubVersion")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<string>("GoogleBooksId")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Isbn")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("PublishedDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Publisher")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Rights")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Subject")
                                .HasMaxLength(300)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Uuid")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT");

                            b1.HasKey("BookId");

                            b1.ToTable("Books");

                            b1.WithOwner()
                                .HasForeignKey("BookId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Highlight", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.TextRange", "TextRange", b1 =>
                        {
                            b1.Property<Guid>("HighlightId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ChapterId")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ChapterId");

                            b1.Property<int>("EndOffset")
                                .HasColumnType("INTEGER")
                                .HasColumnName("EndOffset");

                            b1.Property<string>("SelectedText")
                                .IsRequired()
                                .HasMaxLength(5000)
                                .HasColumnType("TEXT")
                                .HasColumnName("SelectedText");

                            b1.Property<int>("StartOffset")
                                .HasColumnType("INTEGER")
                                .HasColumnName("StartOffset");

                            b1.HasKey("HighlightId");

                            b1.HasIndex("ChapterId")
                                .HasDatabaseName("IX_Highlights_ChapterId");

                            b1.ToTable("Highlights");

                            b1.WithOwner()
                                .HasForeignKey("HighlightId");
                        });

                    b.Navigation("TextRange")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.LibraryIndex", b =>
                {
                    b.HasOne("Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Entities.ReadingHistory", b =>
                {
                    b.HasOne("Domain.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Domain.Entities.SavedCssStyle", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.CssStyle", "Style", b1 =>
                        {
                            b1.Property<Guid>("SavedCssStyleId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CustomCss")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT")
                                .HasColumnName("CustomCss");

                            b1.Property<string>("FontFamily")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("FontFamily");

                            b1.Property<double>("FontSize")
                                .HasColumnType("REAL")
                                .HasColumnName("FontSize");

                            b1.Property<double>("LetterSpacing")
                                .HasColumnType("REAL")
                                .HasColumnName("LetterSpacing");

                            b1.Property<double>("LineHeight")
                                .HasColumnType("REAL")
                                .HasColumnName("LineHeight");

                            b1.Property<int>("MarginHorizontal")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MarginHorizontal");

                            b1.Property<int>("MarginVertical")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MarginVertical");

                            b1.HasKey("SavedCssStyleId");

                            b1.ToTable("SavedCssStyles");

                            b1.WithOwner()
                                .HasForeignKey("SavedCssStyleId");
                        });

                    b.Navigation("Style")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
